version: '3.8'

services:
  postgres:
    container_name: agempo-client-bd
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: agempo
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres